### ISSUE TITLE
Update Firebase functions compatible with version 1.0

### ISSUE THREAD

**Issue by saipraneethd-zz** [cpavnn/RideShare#21]
The Firebase functions used(^0.5) is no longer compatible with firebase-tools. Hence the Firebase Functions which are written in `index.js`  needs to updated. This [link](https://firebase.google.com/docs/functions/beta-v1-diff) is guide for the updating Firebase Functions from Beta to version 1.0

**Comment by cpavnn** [comment]
oh thanks @saipran7777 , Let me have a look

**Comment by cpavnn** [comment]
Hey @saipran7777 ,
Have you updated the functions to >1.0, If yes can you issue a Pull request,
I will merge into the project.
Thanks!

**Comment by saipraneethd-zz** [comment]
Hi @cpavnn,
 I haven't updated the functions completely as I am new to Firebase Functions.  Can we have a voice call where you can run me through the code and after which I will try to update the Functions?

**Comment by cpavnn** [comment]
I have update the `index.js` following the `Cloud Functions Migration Guide: Beta to version 1.0`, the functions should run fine now
