### ISSUE TITLE
Google Maps API

### ISSUE THREAD

**Issue by liberamiguel** [cpavnn/RideShare#24]
Hi Pavan,

First of all, I need to say that this project is a great idea.
I am trying to use it for my company and I got stuck on the google maps API part. Could not find your email to write directly. Could you help me a bit with this step? I am new to development but used google API a long time ago.

Best Regards

**Comment by cpavnn** [comment]
If your question is around getting/setting the google maps api key, the below link has detailed steps
https://developers.google.com/maps/documentation/javascript/get-api-key
Let me know if you need any other information/help
